### ISSUE TITLE
Turtlebot example problem

### ISSUE THREAD

**Issue by Mostafa95** [erlerobot/gym-gazebo#108]
I am using ubuntu 16.04 , and I followed the installation instructions and managed to install everything (of course after solving many problems) but I arrived at dead end and couldn't run  

> circuit2_turtlebot_lidar_qlearn.py

So first I ran:
```
cd gym_gazebo/envs/installation
bash turtlebot_setup.bash
```

and it executed just fine, then I ran:

```
cd gym-gazebo/examples/turtlebot
python3 circuit2_turtlebot_lidar_qlearn.py
```

 

I got the following output:

```
... logging to /home/mostafa/.ros/log/d71db9b2-225b-11e8-9fb9-2c337a6e106f/roslaunch-Matador-31334.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://Matador:42896/
ros_comm version 1.12.12


SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.12

NODES

auto-starting new master
process[master]: started with pid [31345]
ROS_MASTER_URI=http://Matador:11311/

setting /run_id to d71db9b2-225b-11e8-9fb9-2c337a6e106f
core service [/rosout] found
Roscore launched!
Gazebo launched!
WARN: Environment '<class 'gym_gazebo.envs.turtlebot.gazebo_circuit2_turtlebot_lidar.GazeboCircuit2TurtlebotLidarEnv'>' has deprecated methods. Compatibility code invoked.
... logging to /home/mostafa/.ros/log/d71db9b2-225b-11e8-9fb9-2c337a6e106f/roslaunch-Matador-31378.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

WARNING: Metapackage "ecl_lite" must buildtool_depend on catkin.
WARNING: Metapackage "ecl_lite" should not have other dependencies besides a buildtool_depend on catkin and run_depends.
WARNING: Metapackage "ecl_tools" must buildtool_depend on catkin.
WARNING: Metapackage "ecl_tools" should not have other dependencies besides a buildtool_depend on catkin and run_depends.
started roslaunch server http://Matador:42685/

SUMMARY
========

PARAMETERS
 * /bumper2pointcloud/pointcloud_radius: 0.24
 * /cmd_vel_mux/yaml_cfg_file: /home/mostafa/gym...
 * /robot_description: <?xml version="1....
 * /robot_state_publisher/publish_frequency: 30.0
 * /rosdistro: kinetic
 * /rosversion: 1.12.12
 * /use_sim_time: True

NODES
  /
    bumper2pointcloud (nodelet/nodelet)
    cmd_vel_mux (nodelet/nodelet)
    gazebo (gazebo_ros/gzserver)
    mobile_base_nodelet_manager (nodelet/nodelet)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    spawn_turtlebot_model (gazebo_ros/spawn_model)

ROS_MASTER_URI=http://Matador:11311/

WARNING: Metapackage "ecl_lite" must buildtool_depend on catkin.
WARNING: Metapackage "ecl_lite" should not have other dependencies besides a buildtool_depend on catkin and run_depends.
WARNING: Metapackage "ecl_tools" must buildtool_depend on catkin.
WARNING: Metapackage "ecl_tools" should not have other dependencies besides a buildtool_depend on catkin and run_depends.
process[gazebo-1]: started with pid [31420]
process[spawn_turtlebot_model-2]: started with pid [31424]
process[mobile_base_nodelet_manager-3]: started with pid [31425]
process[cmd_vel_mux-4]: started with pid [31426]
process[bumper2pointcloud-5]: started with pid [31432]
process[robot_state_publisher-6]: started with pid [31448]
WARNING: Metapackage "ecl_lite" must buildtool_depend on catkin.
WARNING: Metapackage "ecl_lite" should not have other dependencies besides a buildtool_depend on catkin and run_depends.
WARNING: Metapackage "ecl_tools" must buildtool_depend on catkin.
WARNING: Metapackage "ecl_tools" should not have other dependencies besides a buildtool_depend on catkin and run_depends.
WARNING: Metapackage "ecl_lite" must buildtool_depend on catkin.
WARNING: Metapackage "ecl_lite" should not have other dependencies besides a buildtool_depend on catkin and run_depends.
WARNING: Metapackage "ecl_tools" must buildtool_depend on catkin.
WARNING: Metapackage "ecl_tools" should not have other dependencies besides a buildtool_depend on catkin and run_depends.
[ INFO] [1520463851.278185261]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1520463851.278964093]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1520463852.455408574, 2.780000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1520463852.510464508, 41.290000000]: Physics dynamic reconfigure ready.
[ERROR] [1520463852.671509644, 91.520000000]: Failed to load nodelet [/cmd_vel_mux] of type [yocs_cmd_vel_mux/CmdVelMuxNodelet] even after refreshing the cache: Could not find library corresponding to plugin yocs_cmd_vel_mux/CmdVelMuxNodelet. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[ERROR] [1520463852.671563354, 91.520000000]: The error before refreshing the cache was: Could not find library corresponding to plugin yocs_cmd_vel_mux/CmdVelMuxNodelet. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[FATAL] [1520463852.671688275, 91.520000000]: Failed to load nodelet '/cmd_vel_mux` of type `yocs_cmd_vel_mux/CmdVelMuxNodelet` to manager `mobile_base_nodelet_manager'
[ERROR] [1520463852.713516374, 98.850000000]: Failed to load nodelet [/bumper2pointcloud] of type [kobuki_bumper2pc/Bumper2PcNodelet] even after refreshing the cache: Could not find library corresponding to plugin kobuki_bumper2pc/Bumper2PcNodelet. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[ERROR] [1520463852.713553838, 98.850000000]: The error before refreshing the cache was: Could not find library corresponding to plugin kobuki_bumper2pc/Bumper2PcNodelet. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[FATAL] [1520463852.713779650, 98.850000000]: Failed to load nodelet '/bumper2pointcloud` of type `kobuki_bumper2pc/Bumper2PcNodelet` to manager `mobile_base_nodelet_manager'
[cmd_vel_mux-4] process has died [pid 31426, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load yocs_cmd_vel_mux/CmdVelMuxNodelet mobile_base_nodelet_manager cmd_vel_mux/output:=mobile_base/commands/velocity __name:=cmd_vel_mux __log:=/home/mostafa/.ros/log/d71db9b2-225b-11e8-9fb9-2c337a6e106f/cmd_vel_mux-4.log].
log file: /home/mostafa/.ros/log/d71db9b2-225b-11e8-9fb9-2c337a6e106f/cmd_vel_mux-4*.log
[spawn_turtlebot_model-2] process has finished cleanly
log file: /home/mostafa/.ros/log/d71db9b2-225b-11e8-9fb9-2c337a6e106f/spawn_turtlebot_model-2*.log
[bumper2pointcloud-5] process has died [pid 31432, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load kobuki_bumper2pc/Bumper2PcNodelet mobile_base_nodelet_manager bumper2pointcloud/pointcloud:=mobile_base/sensors/bumper_pointcloud bumper2pointcloud/core_sensors:=mobile_base/sensors/core __name:=bumper2pointcloud __log:=/home/mostafa/.ros/log/d71db9b2-225b-11e8-9fb9-2c337a6e106f/bumper2pointcloud-5.log].
log file: /home/mostafa/.ros/log/d71db9b2-225b-11e8-9fb9-2c337a6e106f/bumper2pointcloud-5*.log
[ INFO] [1520463853.043422581, 98.850000000]: Camera Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1520463853.046777295, 98.850000000]: Camera Plugin (ns = /)  <tf_prefix_>, set to ""
[ INFO] [1520463853.103127516, 98.850000000]: Laser Plugin: Using the 'robotNamespace' param: '/'
[ INFO] [1520463853.103217342, 98.850000000]: Starting Laser Plugin (ns = /)
[ INFO] [1520463853.106123843, 98.850000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
EP: 1 - [alpha: 0.2 - gamma: 0.8 - epsilon: 0.9] - Reward: 1684     Time: 0:00:45
Traceback (most recent call last):
  File "circuit2_turtlebot_lidar_qlearn.py", line 51, in <module>
    observation = env.reset()
  File "/home/mostafa/.local/lib/python3.5/site-packages/gym/wrappers/monitor.py", line 37, in reset
    self._before_reset()
  File "/home/mostafa/.local/lib/python3.5/site-packages/gym/wrappers/monitor.py", line 185, in _before_reset
    self.stats_recorder.before_reset()
  File "/home/mostafa/.local/lib/python3.5/site-packages/gym/wrappers/monitoring/stats_recorder.py", line 68, in before_reset
    raise error.Error("Tried to reset environment which is not done. While the monitor is active for {}, you cannot call reset() unless the episode is over.".format(self.env_id))
gym.error.Error: Tried to reset environment which is not done. While the monitor is active for GazeboCircuit2TurtlebotLidar-v0, you cannot call reset() unless the episode is over.

```
I tried solutions mention here [#22](https://github.com/erlerobot/gym-gazebo/issues/22) and [#60](https://github.com/erlerobot/gym-gazebo/issues/60)  but nothing worked.

So what should I do

**Comment by Mostafa95** [comment]
Also when I ran  

> bash setup_kinetic.bash

the following error appeared 

> Error: Packages with unknown build types exist
> Can not build workspace with packages of unknown build_type
> 
These are the unknown packages:

![gym](https://user-images.githubusercontent.com/13853672/37153645-1200f2da-22e6-11e8-8fd0-f530284b15df.png)

**Comment by Mostafa95** [comment]
I tried to install everything again from scratch, and followed this issue [here](https://github.com/erlerobot/gym-gazebo/issues/110) which probably was the solution to my original problem, but I am not quite sure. so now example  circuit2_turtlebot_lidar_qlearn.py runs perfectly .
