### ISSUE TITLE
Problem when running the turtlebot example

### ISSUE THREAD

**Issue by Bobobs** [erlerobot/gym-gazebo#113]
Everything is install correctly and finished `bash kinetic_setup.bash` without any problems.

Afterwards `~/gym-gazebo/gym_gazebo/envs/turtlebot$ python3 gazebo_circuit2_turtlebot_lidar.py`

Also fine. But when I run `~/gym-gazebo/examples/turtlebot$ python3 circuit2_turtlebot_lidar_qlearn.py`
I get the following

```
Traceback (most recent call last):
  File "circuit2_turtlebot_lidar_qlearn.py", line 25, in <module>
    env = gym.make('GazeboCircuit2TurtlebotLidar-v0')
  File "/home/wasp2/.local/lib/python3.5/site-packages/gym/envs/registration.py", line 163, in make
    return registry.make(id)
  File "/home/wasp2/.local/lib/python3.5/site-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/wasp2/.local/lib/python3.5/site-packages/gym/envs/registration.py", line 86, in make
    env = cls(**self._kwargs)
  File "/home/wasp2/gym-gazebo/gym_gazebo/envs/turtlebot/gazebo_circuit2_turtlebot_lidar.py", line 20, in __init__
    gazebo_env.GazeboEnv.__init__(self, "GazeboCircuit2TurtlebotLidar_v0.launch")
  File "/home/wasp2/gym-gazebo/gym_gazebo/envs/gazebo_env.py", line 20, in __init__
    port = os.environ["ROS_PORT_SIM"]
  File "/usr/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'ROS_PORT_SIM'
```
Any ideas? Thnx

**Comment by ahcorde** [comment]
You need to define the port that ROS will use:

```
export ROS_PORT_SIM=11311
```

**Comment by Bobobs** [comment]
Yes you are right. I was reported in #59 and #65 as well and I somehow missed them both.
Thank you and sorry for the inconvenience.
