### ISSUE TITLE
Can't import gym_gazebo after run the script (which in the INSTALL.md) 

### ISSUE THREAD

**Issue by sxwgit** [erlerobot/gym-gazebo#227]
I installed gym-gazebo successfully and I can import the gym_gazebo.

> (gail) root@songxw-pc:gym-gazebo# sudo pip install -e .
> Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
> Obtaining file:///home/songxw/git/gym-gazebo
> Requirement already satisfied: gym>=0.2.3 in /usr/local/lib/python3.5/dist-packages (from gym-gazebo==0.0.2) (0.12.0)
> Requirement already satisfied: scipy in /usr/lib/python3/dist-packages (from gym>=0.2.3->gym-gazebo==0.0.2) (0.17.0)
> Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python3.5/dist-packages (from gym>=0.2.3->gym-gazebo==0.0.2) (1.16.0)
> Requirement already satisfied: requests>=2.0 in /usr/lib/python3/dist-packages (from gym>=0.2.3->gym-gazebo==0.0.2) (2.9.1)
> Requirement already satisfied: six in /usr/lib/python3/dist-packages (from gym>=0.2.3->gym-gazebo==0.0.2) (1.10.0)
> Requirement already satisfied: pyglet>=1.2.0 in /usr/local/lib/python3.5/dist-packages (from gym>=0.2.3->gym-gazebo==0.0.2) (1.3.2)
> Requirement already satisfied: future in /usr/local/lib/python3.5/dist-packages (from pyglet>=1.2.0->gym>=0.2.3->gym-gazebo==0.0.2) (0.17.1)
> Installing collected packages: gym-gazebo
>   Found existing installation: gym-gazebo 0.0.2
>     Can't uninstall 'gym-gazebo'. No files were found to uninstall.
>   Running setup.py develop for gym-gazebo
> **Successfully installed gym-gazebo**
> (gail) root@songxw-pc:gym-gazebo# python
> Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56) 
> [GCC 7.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> import gym_gazebo
>
> 

BUT , after I  run the script 
```
cd gym_gazebo/examples/scripts_turtlebot
python circuit2_turtlebot_lidar_qlearn.py
```
I get an error that 

`ImportError: No module named 'gym_gazebo'`

> (gail) root@songxw-pc:turtlebot# python circuit2_turtlebot_lidar_qlearn.py
> Traceback (most recent call last):
>   File "circuit2_turtlebot_lidar_qlearn.py", line 4, in <module>
>     import gym_gazebo
>  ImportError: No module named 'gym_gazebo'
> (gail) root@songxw-pc:turtlebot# python
> Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56) 
> [GCC 7.3.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
>  import gym_gazebo
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: No module named 'gym_gazebo'
> import gym_gazebo
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: No module named 'gym_gazebo'
> 

My system is ubuntu 16.04.
Any idea how to solve this ?
Best regards.

**Comment by sxwgit** [comment]
```
songxw@songxw-pc:~$ conda activate gail
(gail) songxw@songxw-pc:~$ python
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gym_gazebo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'gym_gazebo'
>>> 
[1]+  已停止               python
(gail) songxw@songxw-pc:~$ cd git/gym-gazebo/
(gail) songxw@songxw-pc:gym-gazebo$ pip install -e .
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///home/songxw/git/gym-gazebo
    Complete output from command python setup.py egg_info:
    running egg_info
    writing top-level names to gym_gazebo.egg-info/top_level.txt
    error: [Errno 13] Permission denied: 'gym_gazebo.egg-info/top_level.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/songxw/git/gym-gazebo/
You are using pip version 19.0.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(gail) songxw@songxw-pc:gym-gazebo$ python
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gym_gazebo
>>> 

```
It seems like I must run` pip install ` in gym-gazebo so that I can import gym_gazebo, I dont know how to solve this problem,help!
