### ISSUE TITLE
Error on script_turtlebot

### ISSUE THREAD

**Issue by MilowB** [erlerobot/gym-gazebo#26]
After loading scripts with `bash turtlebot_setup.bash`, I try to run `python circuit2_turtlebot_lidar_qlearn.py`

I got this error :

> [2017-05-04 13:15:48,648] Making new env: GazeboCircuit2TurtlebotLidar-v0
Traceback (most recent call last):
  File "circuit2_turtlebot_lidar_qlearn.py", line 25, in <module>
    env = gym.make('GazeboCircuit2TurtlebotLidar-v0')
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 161, in make
    return registry.make(id)
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 17, in load
    result = entry_point.load(False)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/home/epulinfo34/gym-gazebo/gym_gazebo/envs/__init__.py", line 12, in <module>
    from gym_gazebo.envs.gazebo_erlecopter_hover import GazeboErleCopterHoverEnv
  File "/home/epulinfo34/gym-gazebo/gym_gazebo/envs/gazebo_erlecopter_hover.py", line 14, in 
module  from mavros_msgs.msg import OverrideRCIn
    ImportError: No module named `msg`

`ros-indigo-mavros-msgs` and `ros-indigo-mavros` are already installed.

Any idea how to solve this ?

**Comment by imuguruza** [comment]
Please refer to [Erle Robotics](http://forum.erlerobotics.com/) forum for technical issues.
Check if you're sourcing corretly MAVROS.
