### ISSUE TITLE
baselines import agent error

### ISSUE THREAD

**Issue by jacknlliu** [erlerobot/gym-gazebo#63]
I tested scara gazebo example with the following steps but get `baselines` import error.

```sh
cd gym_gazebo/envs/installation
bash scara_setup.bash
```

```sh
cd examples/modular_scara
python3 modular_scara_3dof_qlearn.py
```
Then it prints
```sh
Traceback (most recent call last):
  File "modular_scara_3dof_qlearn.py", line 39, in <module>
    env = gym.make('GazeboModularScara3DOF-v2')
  File "/usr/local/lib/python3.5/dist-packages/gym/envs/registration.py", line 164, in make
    return registry.make(id)
  File "/usr/local/lib/python3.5/dist-packages/gym/envs/registration.py", line 122, in make
    env = spec.make()
  File "/usr/local/lib/python3.5/dist-packages/gym/envs/registration.py", line 88, in make
    cls = load(self._entry_point)
  File "/usr/local/lib/python3.5/dist-packages/gym/envs/registration.py", line 17, in load
    result = entry_point.load(False)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ros/data/gym-gazebo/gym_gazebo/envs/modular_scara/__init__.py", line 1, in <module>
    from gym_gazebo.envs.modular_scara.gazebo_modular_scara_3dof import GazeboModularScara3DOFEnv
  File "/home/ros/data/gym-gazebo/gym_gazebo/envs/modular_scara/gazebo_modular_scara_3dof.py", line 23, in <module>
    from baselines.agent.scara_arm.tree_urdf import treeFromFile # For KDL Jacobians
ImportError: No module named 'baselines.agent'
```

**Comment by vmayoral** [comment]
Hello @jacknlliu,

The SCARA environment is a work in progress and we're still testing many things on it. We haven't put time into making it easy to reproduce so it's normal that you get that and other errors. I believe there're several missing files that aren't open just yet.

If you still have strong interest on this environments and would like to access it, reach me out at victor at erlerobotics.com while introducing what are you up to. I might be able to help.
